### ISSUE TITLE
How to make initial geometry data uneditable

### ISSUE THREAD

**Issue by VCodepp** [codeofsumit/leaflet.pm#416] opened 2019-03-27 12:33 UTC
Hello there . I have a geojson file and I get it with ajax. but I want to prevent the editing of the geometries I load during startup. Only the ones that are added with PM should be editable.
How can i do it ?
i used generate geojson value  = [http://geojson.io/#map=15/40.9933/29.0527](http://geojson.io/#map=15/40.9933/29.0527)

**Comment by VCodepp** [comment] 2019-03-27 14:19
I solved. 

` L.geoJSON(data, { style: polystyle, pmIgnore: true }).addTo(map)`

**Comment by VCodepp** [comment] 2019-03-28 09:11
PmIgnore does not work in 'erase mode'.

**Comment by codeofsumit** [comment] 2019-04-12 20:11
@VCodepp what data are you adding? Polygons? Circles?

**Comment by codeofsumit** [comment] 2019-04-12 20:30
In my tests, it works fine. Can you provide a JSfiddle where it's not working?

**Comment by VCodepp** [comment] 2019-04-15 08:11
I'm sorry for the late reply.

[https://jsfiddle.net/vcode/acgebzj5/41/](https://jsfiddle.net/vcode/acgebzj5/41/)

Click any layer in the delete mode. you'll see that you've removed them all.

**Comment by codeofsumit** [comment] 2019-04-16 18:31
Ah thank you. This is a duplicate of https://github.com/codeofsumit/leaflet.pm/issues/401 and will be fixed in the next release 👍

**Closed by codeofsumit** 2019-04-16 18:31 UTC
Labels: repro needed
