### ISSUE TITLE
after firing map.pm.enableDraw(...) - on each "mousemove" event getting error "Cannot read property 'lat' of null"

### ISSUE THREAD

**Issue by DavidLore** [codeofsumit/leaflet.pm#257] opened 2017-11-28 16:23 UTC
Hey there,

First, I have to say that despite the error that promping on console, the behaviour of the functionality is great. The result is pure Rectangle and the working progress is great. 

**The operation :** 

I'm trying to draw few shapes using leaflet.pm, and I found some troubles while using the method:
`map.pm.enableDraw("Rectangle", {
      drawing: true,
      // snapping
      snappable: true,
      snapDistance: 20,
      allowSelfIntersection: true, 
      finishOn: 'dblclick', 
      templineStyle: {
        color: 'blue'
      },
      hintlineStyle: {
        color: 'blue',
        dashArray: [5, 5]
      },
      cursorMarker: true,
      pathOptions: {
        color: 'red',
        fillColor: 'orange',
        fillOpacity: 0.7
      },
      markerStyle: {
        opacity: 0.5,
        draggable: true,
      }
    });`

Then, when I'm moving with the cursor around the leaflet map I'm getting error.
I already debugged the leaflet module all the day and I found the source of the bug : 
 In the function : 
`
// @method latLngToLayerPoint(latlng: LatLng): Point

	// Given a geographical coordinate, returns the corresponding pixel coordinate

	// relative to the [origin pixel](#map-getpixelorigin)

latLngToLayerPoint: function (latlng) {
			     var projectedPoint = this.project(toLatLng(latlng))._round();
			     return projectedPoint._subtract(this.getPixelOrigin());
		}
`
The function getting the parameter _latlng_ that expecting to be type of _LatLng_ but instead he getting
an array of 17 elements of type _LatLng_.

![arrayoflatlng](https://user-images.githubusercontent.com/23473818/33330099-9e963260-d466-11e7-8462-5ff7f888c5c0.png)

So - when executing the function `toLatLng(latlng)` it returns null, and then this null sended to 'this.project' method and then it throws an error to console. 

So I tried to change and manipulate the code in purpose to avoid error's on console, and I have done it, but the performance of the drawing Rectangle process (while moving the cursor around the map) became awful (just getting too slow when mouse move during the draw), so I can't really found a good solution to the error's on console.

* Needless to say that I already tried to wrap this code area by try & catch but I haven't find a solution that will work well.
* I also tried to send each element of array with for-loop, and also tried to send only the last/first point in the array. All this workarounds has led me to heavy performance issue (But the error's on console disappeared).

I want to say again - the performance when I getting the error's on console were great, but I want to avoid the error's that coming from the leaflet module.

By the way, I'm using the latest version of leaflet : "1.2.0+HEAD.1ac320b"

Thank you friends.

**Comment by codeofsumit** [comment] 2017-12-01 01:39
hey @DavidLore. Do you mind using ``` to wrap the provided code so I actually know what options you passed? If I copy that, most of the code is commented out.

Also: if you can provide a JSfiddle showing the problem, it'd be much more helpful for me to get to the bottom of this.

Thanks for your help!

**Comment by royhobbstn** [comment] 2017-12-09 02:24
@codeofsumit I'm having the same issue.  Here's a JSFiddle of the problem.
https://jsfiddle.net/dqnzts6a/1/
It seems to be triggered by the combination of geojson and leaflet.pm.

**Comment by codeofsumit** [comment] 2018-03-11 21:38
Haven't been able to reproduce this yet, sorry. I'll close this issue for now. Feel free to reopen the issue with a JSfiddle and error reproduction 👍

**Closed by codeofsumit** 2018-03-11 21:38 UTC
Labels: repro needed

**Comment by smeijer** [comment] 2018-05-03 09:54
I guess #249 is related and possibly the same issue.
