### ISSUE TITLE
Cannot snap Marker to a new Polyline

### ISSUE THREAD

**Issue by gorczii** [codeofsumit/leaflet.pm#330] opened 2018-08-14 14:46 UTC
Hey :) I found a bug when adding a new shape and trying to snap marker to it.
You can reproduce it on the demo [](https://leafletpm.now.sh/) following these steps: 
- Place new marker anywhere
- Add new polyline/polygon/any other shape
- Try to snap a new marker on the previously created shape (this is where the problem occurs - it's impossible to snap the newly created marker to this shape).

Is there any way to solve this problem?

Best regards!

**Comment by codeofsumit** [comment] 2018-08-30 05:45
seem to be working for me 🤔 

![snapping](https://user-images.githubusercontent.com/2399810/44831868-afa07d00-ac28-11e8-9c28-d3f3415a48b2.gif)

**Comment by codeofsumit** [comment] 2018-10-14 16:55
I will close this issue now. Please reopen with a repro if the issue is still present 👍

**Closed by codeofsumit** 2018-10-14 16:55 UTC
Labels: repro needed
