### ISSUE TITLE
Prevent removal of markers on right-click in edit mode?

### ISSUE THREAD

**Issue by Epthelyn** [codeofsumit/leaflet.pm#258] opened 2017-11-29 17:08 UTC
Hi,

Is it possible to prevent markers being removed when right clicked on in edit mode?

I have markers set up in such a way that if a user right clicks on them they get additional options to interact with the marker and other things, but if the user is in edit mode (e.g. they've just moved marker from point A to point B and then want to change value X without selecting from the menu) at the time, the marker is removed. Whilst I can get around this by immediately recreating the marker from stored data and making sure every reference to it is restored correctly it would be great if I could avoid having to do that; depending on the marker that process can be fairly complicated.

Thanks.

**Comment by codeofsumit** [comment] 2017-11-30 20:38
@Epthelyn where you able to solve the issue? Could you comment on what made you close the issue? Thanks a lot!

**Comment by Epthelyn** [comment] 2017-11-30 23:24
Sorry, thought I'd left a response before closing it. My mistake!

Found the line causing the behaviour in L.PM.Edit.Marker.js (lines 35-36) and removed it from my local copy:
```
// enable removal for the marker
        this._layer.on('contextmenu', this._removeMarker, this);
```
A working alternative was to activate an equivalent of the disable() (located within the same file) and remove the listener on a case-by-case basis for all markers when edit mode was enabled. However, since that involved poking around variables that probably shouldn't be directed changed and I don't need the right-click deletion for _any_ markers I avoided doing that; removing it entirely did exactly what I needed even if it isn't perhaps the cleanest solution.

**Comment by codeofsumit** [comment] 2017-12-01 01:10
ok, I'll leave this issue open as the library should provide this as an option. Thanks for clarifying, I'll add this into it

**Comment by kayoshi** [comment] 2018-01-18 04:56
@codeofsumit Hi! Did you find the solution to the issue?

**Comment by codeofsumit** [comment] 2018-03-11 21:30
@kayoshi not yet, the problem is we don't have a way to pass options to the toolbars edit button yet 🤔

**Closed** 2018-03-11 21:58 UTC
