### ISSUE TITLE
Problem with 'pm:remove'

### ISSUE THREAD

**Issue by denny123** [codeofsumit/leaflet.pm#181] opened 2017-07-21 12:31 UTC
I have featuregroup layer on map(with layers). If update(or add) layer in featuregroup and after add to map, then fire 'pm:remove' but not to all objects/markers(i dont why), and after some markers(not all) cant removed. Featuregroup set 'pmIgnored:true'.

**Comment by codeofsumit** [comment] 2017-07-21 13:14
hey @denny123, can you provide a JSfiddle to reproduce the issue please?

**Comment by denny123** [comment] 2017-07-21 13:18
i bad know JSfiddle, and i need find code on my script(big and i dont remember where), becouse not now -).

**Comment by denny123** [comment] 2017-07-21 14:44
Not working 'pm:drawend' for marker...

**Comment by codeofsumit** [comment] 2017-07-21 21:31
ok I have an idea of the problem. I will investigate!

**Comment by codeofsumit** [comment] 2017-07-25 08:37
@denny123 so you have to set `pmIgnore` to the individual layers in your featureGroup. The featureGroup in leaflet doesn't accept any options.
If you can't make it work, please create a test case on jsfiddle https://jsfiddle.net/ and I'll help you to figure it out or - if there is an issue with leaflet.pm - can replicate and fix it.

**Comment by denny123** [comment] 2017-07-25 08:43
More information: if pmIgnore:false on featureGroup then remove(if click on marker in featuregroup) from map all layers in feaureGroup, and if pnIgnore:true then remove(if click on marker in featuregroup) only this marker(i need this), but while loading data to feauregroup fire pm:remove too....(

**Comment by codeofsumit** [comment] 2017-07-25 08:46
@denny123 it sounds like a bug but (sorry) your english is very bad and I'm having a hard time to understand the exact usecase to replicate it.

Please just paste the code or create a test case how you use leaflet.pm in your app so I can replicate the issue

**Comment by denny123** [comment] 2017-07-25 09:01
i undestand, i need time.

**Comment by codeofsumit** [comment] 2017-07-25 09:08
this is the branch:
https://github.com/codeofsumit/leaflet.pm/pull/186

**Comment by denny123** [comment] 2017-07-25 09:11
this fix in new version?

**Comment by codeofsumit** [comment] 2017-07-25 09:48
shit, sorry, wrong issue

**Comment by denny123** [comment] 2017-07-25 15:05
https://jsfiddle.net/xp4rsqb6/63/ - here not all error, but while many 'remove' if remove marker.(i dont speak english).

**Comment by denny123** [comment] 2017-07-26 06:48
i dont undastand - this fixed or no?

**Comment by codeofsumit** [comment] 2017-07-26 07:17
no this isn't fixed yet. I accidentally mentioned this issue in a git commit and Github automatically closed it. Sorry.

It's still open.

**Comment by denny123** [comment] 2017-07-26 07:42
https://jsfiddle.net/xp4rsqb6/75/ - update(if many add then fire remove). I need fire 'pm:remove' only by this plugin(not by clearLayers and other)?

**Comment by codeofsumit** [comment] 2017-07-26 08:00
Thanks! Ok I think I know what the issue is.

You want `pm:remove` to only be fired when you delete a layer via leaflet.pm, not when you use leaflets own functions like `layer.remove()` - is that correct?

That'd also mean we need a new function to remove layers, like `layer.pm.remove()` and only this would fire `pm:remove`.

Is that correct?

**Comment by denny123** [comment] 2017-07-26 08:04
Yes! Fire 'pm:remove' only if 'map.pm.toggleGlobalRemovalMode(true);' and click on marker(example).

**Comment by denny123** [comment] 2017-07-26 09:07
MORE: if edit marker(drag,editPolygon:true) then fire 'pm:remove' too.

**Comment by codeofsumit** [comment] 2017-07-26 09:33
hmm no the `pm:remove` event should be fired when a layer is removed through leaflet.pm. Doesn't matter if edit mode is enabled or not.
GlobalRemovalMode will also fire `pm:remove` if a layer is removed that way obviously.

**Comment by denny123** [comment] 2017-07-26 09:39
https://jsfiddle.net/xp4rsqb6/77/ -here fire 'pm:remove' when dragend. Yes, if remove fire 'pm:remove', but i think this fire only if click on marker(GlobalRemovalMode enable), otherwise why button remove?

**Comment by codeofsumit** [comment] 2017-08-04 12:17
ok @denny123 I think I won't fix this.

If I understand you correctly, you want `pm:remove` to only fire when GlobalRemovalMode is active.

But `pm:remove` should be fired whenever a layer that is handled by leaflet.pm is removed from the map. Doesn't matter how.

The Toolbar and the "GlobalRemovalMode" is just a graphical functionality for something that can be done via the API too.

If you want leaflet.pm to ignore layers, give them `pmIgnore: true` as an option upon creating them and `pm:remove` won't fire for them.

I'll close the issue now.

In case I did not understand you correctly, please do a SIMPLE jsfiddle with comments and alerts so I can understand what exactly you want to achieve.

**Closed by codeofsumit** 2017-08-04 12:17 UTC

**Comment by denny123** [comment] 2017-08-04 13:17
Ok, thnx.
