### ISSUE TITLE
Layer deletion should respect "pmIgnore"

### ISSUE THREAD

**Issue by thomasvoigt** [codeofsumit/leaflet.pm#172] opened 2017-07-05 09:07 UTC
Hi there!

Our use case involves a mix of user-editable layers and read-only layers, tagged with "pmIgnore". Unfortunately, deleting those layers is still possible.

Shouldn't "delete" respect a layer's "pmIgnore" setting, too?

Thanks and best regards,
Thomas

**Comment by codeofsumit** [comment] 2017-07-05 09:39
Hi @thomasvoigt. Hmm good point. The "delete" functionality is leaflets own `layer.delete`, obviously I can't / don't want to hijack that.
But if your users are using the toolbars "delete button" and still can remove layers, it sounds like a mistake on my part and I will fix it asap.
Can you give me feedback real quick if that's the case?

**Comment by thomasvoigt** [comment] 2017-07-05 09:52
Yep, users can delete "pmIgnore"-protected layers using the toolbar-button-of-mass-destruction.

**Comment by codeofsumit** [comment] 2017-07-05 10:00
ok then this is a bug and I'll fix it. Please note, I'm on vacation starting tomorrow. I hope to fix and release a new version in the week starting at 17th of July 🤞 .

**Comment by thomasvoigt** [comment] 2017-07-05 10:44
Thanks for getting back to me so quickly, enjoy your holiday!

**Comment by josejaner** [comment] 2017-07-09 01:57
"pmIgnore", not work in edit mode, using the toolbar

**Comment by josejaner** [comment] 2017-07-09 02:11
If a geojson is large, in editing mode it takes a long time to activate the vertices, I recommend selecting the element before.
sorry for my English
! Excellent plugin!

**Comment by codeofsumit** [comment] 2017-07-15 14:37
@josejaner please provide a JSfiddle or other demo so I can replicate the issue with the Toolbars Edit-Button.

**Comment by codeofsumit** [comment] 2017-07-18 11:21
@josejaner I can't reproduce your problem. Please create a separate issue with an example - this issue will be fixed with the next release.

**Closed** 2017-07-18 11:24 UTC
Labels: bug
