### ISSUE TITLE
Another conflict with leaflet-measure-path

### ISSUE THREAD

**Issue by sletszarr** [codeofsumit/leaflet.pm#151] opened 2017-04-24 05:00 UTC
Hi, I have a similar issue with this one #116 
and the fix is still not working for me..

Simply by adding leaflet-measure-path.js on your demo page,
when a polygon is dragged, it'll still throw an error of:

```
Uncaught TypeError: Cannot read property 'redraw' of undefined
    at e._onLayerDrag (Drag.js:113)
    at e._dragMixinOnMouseMove (Drag.js:69)
    at e.fire (leaflet.js:5)
    at e._fireDOMEvent (leaflet.js:6)
    at e._handleDOMEvent (leaflet.js:6)
    at HTMLDivElement.h (leaflet.js:6)
```

**Comment by codeofsumit** [comment] 2017-04-29 21:37
The issue is again with leaflet-measure-path.
I reported the issue [here](https://github.com/ProminentEdge/leaflet-measure-path/issues/18) and proposed another fix via [this PR](https://github.com/ProminentEdge/leaflet-measure-path/pull/19).

As soon as this is merged, the issue is gone.

**Closed by codeofsumit** 2017-04-29 21:37 UTC

**Comment by sletszarr** [comment] 2017-05-04 07:56
Hi, sorry for the late reply
Thank you very much for the fix :D
